// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: mail.proto

package community

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MailService service

type MailService interface {
	SendMail(ctx context.Context, in *SendMailRequest, opts ...client.CallOption) (*SendMailResponse, error)
}

type mailService struct {
	c    client.Client
	name string
}

func NewMailService(name string, c client.Client) MailService {
	return &mailService{
		c:    c,
		name: name,
	}
}

func (c *mailService) SendMail(ctx context.Context, in *SendMailRequest, opts ...client.CallOption) (*SendMailResponse, error) {
	req := c.c.NewRequest(c.name, "MailService.SendMail", in)
	out := new(SendMailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MailService service

type MailServiceHandler interface {
	SendMail(context.Context, *SendMailRequest, *SendMailResponse) error
}

func RegisterMailServiceHandler(s server.Server, hdlr MailServiceHandler, opts ...server.HandlerOption) error {
	type mailService interface {
		SendMail(ctx context.Context, in *SendMailRequest, out *SendMailResponse) error
	}
	type MailService struct {
		mailService
	}
	h := &mailServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MailService{h}, opts...))
}

type mailServiceHandler struct {
	MailServiceHandler
}

func (h *mailServiceHandler) SendMail(ctx context.Context, in *SendMailRequest, out *SendMailResponse) error {
	return h.MailServiceHandler.SendMail(ctx, in, out)
}
