// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.6.1
// source: user-relation.proto

package community

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FellowUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FellowUserId uint32 `protobuf:"varint,2,opt,name=fellow_user_id,json=fellowUserId,proto3" json:"fellow_user_id,omitempty"`
}

func (x *FellowUserRequest) Reset() {
	*x = FellowUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_relation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FellowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FellowUserRequest) ProtoMessage() {}

func (x *FellowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_relation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FellowUserRequest.ProtoReflect.Descriptor instead.
func (*FellowUserRequest) Descriptor() ([]byte, []int) {
	return file_user_relation_proto_rawDescGZIP(), []int{0}
}

func (x *FellowUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FellowUserRequest) GetFellowUserId() uint32 {
	if x != nil {
		return x.FellowUserId
	}
	return 0
}

type FellowUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FellowUserReply) Reset() {
	*x = FellowUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_relation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FellowUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FellowUserReply) ProtoMessage() {}

func (x *FellowUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_relation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FellowUserReply.ProtoReflect.Descriptor instead.
func (*FellowUserReply) Descriptor() ([]byte, []int) {
	return file_user_relation_proto_rawDescGZIP(), []int{1}
}

type GetFellowCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetFellowCountRequest) Reset() {
	*x = GetFellowCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_relation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFellowCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFellowCountRequest) ProtoMessage() {}

func (x *GetFellowCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_relation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFellowCountRequest.ProtoReflect.Descriptor instead.
func (*GetFellowCountRequest) Descriptor() ([]byte, []int) {
	return file_user_relation_proto_rawDescGZIP(), []int{2}
}

func (x *GetFellowCountRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFellowCountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FellowCount   uint32 `protobuf:"varint,1,opt,name=fellow_count,json=fellowCount,proto3" json:"fellow_count,omitempty"`
	FellowerCount uint32 `protobuf:"varint,2,opt,name=fellower_count,json=fellowerCount,proto3" json:"fellower_count,omitempty"`
}

func (x *GetFellowCountReply) Reset() {
	*x = GetFellowCountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_relation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFellowCountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFellowCountReply) ProtoMessage() {}

func (x *GetFellowCountReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_relation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFellowCountReply.ProtoReflect.Descriptor instead.
func (*GetFellowCountReply) Descriptor() ([]byte, []int) {
	return file_user_relation_proto_rawDescGZIP(), []int{3}
}

func (x *GetFellowCountReply) GetFellowCount() uint32 {
	if x != nil {
		return x.FellowCount
	}
	return 0
}

func (x *GetFellowCountReply) GetFellowerCount() uint32 {
	if x != nil {
		return x.FellowerCount
	}
	return 0
}

type FellowUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *FellowUserInfo) Reset() {
	*x = FellowUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_relation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FellowUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FellowUserInfo) ProtoMessage() {}

func (x *FellowUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_relation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FellowUserInfo.ProtoReflect.Descriptor instead.
func (*FellowUserInfo) Descriptor() ([]byte, []int) {
	return file_user_relation_proto_rawDescGZIP(), []int{4}
}

func (x *FellowUserInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FellowUserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetFellowersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Skip   uint32 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit  uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetFellowersRequest) Reset() {
	*x = GetFellowersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_relation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFellowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFellowersRequest) ProtoMessage() {}

func (x *GetFellowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_relation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFellowersRequest.ProtoReflect.Descriptor instead.
func (*GetFellowersRequest) Descriptor() ([]byte, []int) {
	return file_user_relation_proto_rawDescGZIP(), []int{5}
}

func (x *GetFellowersRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFellowersRequest) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetFellowersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFellowersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint32            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*FellowUserInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFellowersReply) Reset() {
	*x = GetFellowersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_relation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFellowersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFellowersReply) ProtoMessage() {}

func (x *GetFellowersReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_relation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFellowersReply.ProtoReflect.Descriptor instead.
func (*GetFellowersReply) Descriptor() ([]byte, []int) {
	return file_user_relation_proto_rawDescGZIP(), []int{6}
}

func (x *GetFellowersReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetFellowersReply) GetData() []*FellowUserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFellowedUsersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Skip   uint32 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit  uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetFellowedUsersRequest) Reset() {
	*x = GetFellowedUsersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_relation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFellowedUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFellowedUsersRequest) ProtoMessage() {}

func (x *GetFellowedUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_relation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFellowedUsersRequest.ProtoReflect.Descriptor instead.
func (*GetFellowedUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_relation_proto_rawDescGZIP(), []int{7}
}

func (x *GetFellowedUsersRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFellowedUsersRequest) GetSkip() uint32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetFellowedUsersRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFellowedUsersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFellowedUsersReply) Reset() {
	*x = GetFellowedUsersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_relation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFellowedUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFellowedUsersReply) ProtoMessage() {}

func (x *GetFellowedUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_relation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFellowedUsersReply.ProtoReflect.Descriptor instead.
func (*GetFellowedUsersReply) Descriptor() ([]byte, []int) {
	return file_user_relation_proto_rawDescGZIP(), []int{8}
}

var File_user_relation_proto protoreflect.FileDescriptor

var file_user_relation_proto_rawDesc = []byte{
	0x0a, 0x13, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x11, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x66, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x30, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5f,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x66, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x66, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x3c, 0x0a, 0x0e, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x58, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6b, 0x69,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x4e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6b, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x91,
	0x02, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x46, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12, 0x14,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x18,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_relation_proto_rawDescOnce sync.Once
	file_user_relation_proto_rawDescData = file_user_relation_proto_rawDesc
)

func file_user_relation_proto_rawDescGZIP() []byte {
	file_user_relation_proto_rawDescOnce.Do(func() {
		file_user_relation_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_relation_proto_rawDescData)
	})
	return file_user_relation_proto_rawDescData
}

var file_user_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_relation_proto_goTypes = []interface{}{
	(*FellowUserRequest)(nil),       // 0: FellowUserRequest
	(*FellowUserReply)(nil),         // 1: FellowUserReply
	(*GetFellowCountRequest)(nil),   // 2: GetFellowCountRequest
	(*GetFellowCountReply)(nil),     // 3: GetFellowCountReply
	(*FellowUserInfo)(nil),          // 4: FellowUserInfo
	(*GetFellowersRequest)(nil),     // 5: GetFellowersRequest
	(*GetFellowersReply)(nil),       // 6: GetFellowersReply
	(*GetFellowedUsersRequest)(nil), // 7: GetFellowedUsersRequest
	(*GetFellowedUsersReply)(nil),   // 8: GetFellowedUsersReply
}
var file_user_relation_proto_depIdxs = []int32{
	4, // 0: GetFellowersReply.data:type_name -> FellowUserInfo
	0, // 1: UserRelationService.FellowUser:input_type -> FellowUserRequest
	2, // 2: UserRelationService.GetFellowCount:input_type -> GetFellowCountRequest
	5, // 3: UserRelationService.GetFellowers:input_type -> GetFellowersRequest
	7, // 4: UserRelationService.GetFellowedUsers:input_type -> GetFellowedUsersRequest
	1, // 5: UserRelationService.FellowUser:output_type -> FellowUserReply
	3, // 6: UserRelationService.GetFellowCount:output_type -> GetFellowCountReply
	6, // 7: UserRelationService.GetFellowers:output_type -> GetFellowersReply
	8, // 8: UserRelationService.GetFellowedUsers:output_type -> GetFellowedUsersReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_relation_proto_init() }
func file_user_relation_proto_init() {
	if File_user_relation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_relation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FellowUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_relation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FellowUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_relation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFellowCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_relation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFellowCountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_relation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FellowUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_relation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFellowersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_relation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFellowersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_relation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFellowedUsersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_relation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFellowedUsersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_relation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_relation_proto_goTypes,
		DependencyIndexes: file_user_relation_proto_depIdxs,
		MessageInfos:      file_user_relation_proto_msgTypes,
	}.Build()
	File_user_relation_proto = out.File
	file_user_relation_proto_rawDesc = nil
	file_user_relation_proto_goTypes = nil
	file_user_relation_proto_depIdxs = nil
}
